version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.3-browsers
      
    working_directory: ~/ooek-automation
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --username=$TEST_USER --password=$TEST_PASSWORD --junitxml=test-results/oeek/ooek.xml
      - store_test_results:
          path: test-results

